apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway
  namespace: kong
  labels:
    app: kong-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-gateway
  template:
    metadata:
      labels:
        app: kong-gateway
    spec:
      containers:
      - name: kong-gateway
        image: kong/kong-gateway:3.6.0.0
        env:
          - name: KONG_ROLE
            value: "data_plane"
          - name: KONG_DATABASE
            value: "off"
          - name: KONG_CLUSTER_MTLS
            value: "pki"
          - name: KONG_CLUSTER_CONTROL_PLANE
            value: "$KONG_CLUSTER_CONTROL_PLANE"
          - name: KONG_CLUSTER_SERVER_NAME
            value: "$KONG_CLUSTER_SERVER_NAME"
          - name: KONG_CLUSTER_TELEMETRY_ENDPOINT
            value: "$KONG_CLUSTER_TELEMETRY_ENDPOINT"
          - name: KONG_CLUSTER_TELEMETRY_SERVER_NAME
            value: "$KONG_CLUSTER_TELEMETRY_SERVER_NAME"
          - name: KONG_CLUSTER_CERT
            value: "/etc/secrets/kong-cluster-cert/tls.crt"
          - name: KONG_CLUSTER_CERT_KEY
            value: "/etc/secrets/kong-cluster-cert/tls.key"
          - name: KONG_LUA_SSL_TRUSTED_CERTIFICATE
            value: "system"
          - name: KONG_KONNECT_MODE
            value: "on"
          - name: KONG_VITALS
            value: "off"
        volumeMounts:
          - name: kong-cluster-cert
            mountPath: "/etc/secrets/kong-cluster-cert"
            readOnly: true
      volumes:
        - name: kong-cluster-cert
          secret:
            secretName: kong-cluster-cert