apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: first-upstream-target
  namespace: testing
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /api
        pathType: ImplementationSpecific
        backend:
          service:
            name: echo
            port:
              number: 80