_format_version: "3.0"
_info:
  defaults: {}
  select_tags:
  - first-service-route
_konnect:
  runtime_group_name: default
services:
- connect_timeout: 60000
  enabled: true
  host: httpbin.org
  name: api-service
  path: /anything
  routes:
  - https_redirect_status_code: 426
    name: api-route
    path_handling: v0
    paths:
    - /api
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
