version: "3"

services:
  kong-dp:
    image: kong/kong-gateway:${VERSION}
    ports:
      - "8005:8000/tcp"
      - "8443:8443/tcp"
      - "8100:8100/tcp"
    environment:
      KONG_ROLE: data_plane
      KONG_DATABASE: "off"
      KONG_VITALS: "off"
      KONG_CLUSTER_MTLS: pki
      KONG_CLUSTER_CONTROL_PLANE: ${KONG_CLUSTER_CONTROL_PLANE}
      KONG_CLUSTER_SERVER_NAME: ${KONG_CLUSTER_SERVER_NAME}
      KONG_CLUSTER_TELEMETRY_ENDPOINT:  ${KONG_CLUSTER_TELEMETRY_ENDPOINT}
      KONG_CLUSTER_TELEMETRY_SERVER_NAME: ${KONG_CLUSTER_TELEMETRY_SERVER_NAME}
      KONG_CLUSTER_CERT: ${KONG_CLUSTER_CERT}
      KONG_CLUSTER_CERT_KEY: ${KONG_CLUSTER_CERT_KEY}
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: system
      KONG_KONNECT_MODE: "on"
      KONG_STATUS_LISTEN: "0.0.0.0:8100"
      KONG_LOG_LEVEL: debug